version: "3"

tasks:
  add:
    silent: true
    #prompt: This will create Day {{.CLI_ARGS}}. Continue?
    cmds:
      - echo "Adding Day {{.CLI_ARGS}}"
      - mkdir day{{.CLI_ARGS}}
      - cp tmp/solve.js day{{.CLI_ARGS}}/solve.js
      - cp tmp/data.js day{{.CLI_ARGS}}/data.js
      - cp tmp/sample.js day{{.CLI_ARGS}}/sample.js
      - | # Workaround since taskfile can't parse : properly
        jq '.scripts += { "day{{.CLI_ARGS}}" : "node day{{.CLI_ARGS}}/solve.js" }' package.json > package.bak.json
      - mv package.bak.json package.json
