version: "3"

dotenv: [".env"]

tasks:
  add:
    silent: true
    #prompt: This will create Day {{.CLI_ARGS}}. Continue?
    cmds:
      - echo "Adding Day {{.CLI_ARGS}}"
      - mkdir day{{.CLI_ARGS}}
      - cp tmp/solve.ts day{{.CLI_ARGS}}/solve.ts
      - cp tmp/data.ts day{{.CLI_ARGS}}/data.ts
      - | # Workaround since taskfile can't parse : properly
        jq '.tasks += { "day{{.CLI_ARGS}}" : "deno run --watch day{{.CLI_ARGS}}/solve.ts" }' deno.json > deno.bak.json
      - mv deno.bak.json deno.json
      - sed 's/Day XXX:/Day {{.CLI_ARGS}}:/g' day{{.CLI_ARGS}}/solve.ts > day{{.CLI_ARGS}}/solve.bak.ts
      - mv day{{.CLI_ARGS}}/solve.bak.ts day{{.CLI_ARGS}}/solve.ts
      - sed 's/\/\/ TEMPLATE://g' day{{.CLI_ARGS}}/solve.ts > day{{.CLI_ARGS}}/solve.bak.ts
      - mv day{{.CLI_ARGS}}/solve.bak.ts day{{.CLI_ARGS}}/solve.ts
  fetch:
    silent: true
    vars:
      DATA:
        sh: | # Workaround since taskfile can't parse : properly
            export DATA=$(curl "https://adventofcode.com/2022/day/{{.CLI_ARGS}}/input" -H "cookie: session=$SESSION;")
    cmds:
      - sed 's/\/\/ DATA:/{{.DATA}}:/g' day{{.CLI_ARGS}}/solve.ts > day{{.CLI_ARGS}}/solve.bak.ts
      - mv day{{.CLI_ARGS}}/solve.bak.ts day{{.CLI_ARGS}}/solve.ts

